---
ID: da04b275-8838-4a3a-afee-817cf1fdd2eb
Parent: ef072af6-ef9c-4957-854b-ecc2ef7b3f94
Template: a87a00b1-e6db-45ab-8b54-636fec3b5523
Path: /sitecore/layout/Layouts/Habitat/Project
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20151030T173040Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
